name: where_moe_svitlo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  google_maps_flutter: ^2.2.5
  sqflite: ^2.0.0+3
  path_provider: ^2.0.9
  flutter_svg: ^0.23.0 





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/setting.png
    - assets/images/map.png
    - assets/images/calendar.png
    - assets/images/storm.png
    - assets/images/rain.png
    - assets/images/sun.png
    - assets/images/pharmacy.png
    - assets/images/schedule.png
    - assets/images/wheel.png
    - assets/images/oblst/charkivska.png
    - assets/images/oblst/cherkaska.png
    - assets/images/oblst/chernigivs.png
    - assets/images/oblst/Chernivec.png
    - assets/images/oblst/chersons.png
    - assets/images/oblst/creame.png
    - assets/images/oblst/djitomu.png
    - assets/images/oblst/dnipro.png
    - assets/images/oblst/donbas.png
    - assets/images/oblst/hmelnic.png
    - assets/images/oblst/ivanofrank.png
    - assets/images/oblst/kievska.png
    - assets/images/oblst/kirovogr.png
    - assets/images/oblst/Kyiv.png
    - assets/images/oblst/luganska.png
    - assets/images/oblst/lvivska.png
    - assets/images/oblst/mukoivs.png
    - assets/images/oblst/odesca.png
    - assets/images/oblst/poltavska.png
    - assets/images/oblst/rivnencka.png
    - assets/images/oblst/sumska.png
    - assets/images/oblst/ternop.png
    - assets/images/oblst/Vinnic.png
    - assets/images/oblst/volin.png
    - assets/images/oblst/zakarpats.png
    - assets/images/oblst/zaporiz.png

